version: '3'
services:
  backend:
    image: node:18.13.0
    working_dir: /app/backend
    command: sh -c "npm run start:prod"
    ports:
      - "3300:3300"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app/backend
    networks:
      - my-network

  frontend:
    image: node:18.13.0
    working_dir: /app/frontend
    command: sh -c "npm start"
    ports:
      - "3301:3000"
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app/frontend
    networks:
      - my-network
networks:
  my-network:
    driver: bridge