version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "7050:7050"
    env_file:
      - ./backend/.env
    networks:
      - poker

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "7051:7051"
    env_file:
      - ./frontend/.env
    networks:
      - poker

networks:
  poker:
    driver: bridge