version: '3.8'

services:
  backend:
    image: ${{ secrets.DOCKER_REGISTRY_URL }}/planningpokerclub-backend:latest
    container_name: planningpokerclub-backend
    ports:
      - "7050:7050"
    environment:
      - NODE_ENV=production
    restart: always

  frontend:
    image: ${{ secrets.DOCKER_REGISTRY_URL }}/planningpokerclub-frontend:latest
    container_name: planningpokerclub-frontend
    ports:
      - "7051:3301"
    environment:
      - NODE_ENV=production
    restart: always

networks:
  default:
    driver: bridge
