version: '3.3'

services:
  backend:
    image: ${DOCKER_REGISTRY_URL}/planningpokerclub-backend:latest
    container_name: planningpokerclub-backend
    ports:
      - "7050:3300"
    env_file:
      - ./backend/.env
    restart: always

  frontend:
    image: ${DOCKER_REGISTRY_URL}/planningpokerclub-frontend:latest
    container_name: planningpokerclub-frontend
    ports:
      - "7051:3301"
    env_file:
      - ./frontend/.env
    restart: always

networks:
  default:
    driver: bridge

