version: '3.3'

services:
  planning-mongo:
    container_name: planning-mongo
    image: prismagraphql/mongo-single-replica:4.4.3-bionic
    environment:
      MONGO_INITDB_ROOT_USERNAME: aToCPaEMc31
      MONGO_INITDB_ROOT_PASSWORD: 1DDA67B1974990B57E54EAF7407896F3
      INIT_WAIT_SEC: 3
    ports:
      - 27017:27017