name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: |
            ~/docker-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Log in to Docker Registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login ${{ secrets.DOCKER_REGISTRY_URL }} -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Tag Backend Docker Image
        run: |
          cd ./backend
          docker build -t planningpokerclub-backend:latest .
          docker tag planningpokerclub-backend:latest ${{ secrets.DOCKER_REGISTRY_URL }}/planningpokerclub-backend:latest

      - name: Push Backend Docker Image
        run: |
          docker push ${{ secrets.DOCKER_REGISTRY_URL }}/planningpokerclub-backend:latest

      - name: Build and Tag Frontend Docker Image
        run: |
          cd ./frontend
          docker build -t planningpokerclub-frontend:latest .
          docker tag planningpokerclub-frontend:latest ${{ secrets.DOCKER_REGISTRY_URL }}/planningpokerclub-frontend:latest

      - name: Push Frontend Docker Image
        run: |
          docker push ${{ secrets.DOCKER_REGISTRY_URL }}/planningpokerclub-frontend:latest

      - name: Deploy to VPS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_USER: ${{ secrets.VPS_USER }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_REGISTRY_URL: ${{ secrets.DOCKER_REGISTRY_URL }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_HOST << 'EOF'
            echo "$DOCKER_PASSWORD" | docker login $DOCKER_REGISTRY_URL -u "$DOCKER_USERNAME" --password-stdin
            cd /www/wwwroot/planning-poker-club
            cd backend
            docker run -d --name planningpokerclub-backend -p 7050:7050 $DOCKER_REGISTRY_URL/planningpokerclub-backend:latest
            cd ..
            cd frontend 
            docker run -d --name planningpokerclub-frontend -p 7051:3301 $DOCKER_REGISTRY_URL/planningpokerclub-frontend:latest
          EOF

      - name: Clean up local Docker containers
        run: |
          docker stop backend frontend || true
          docker rm backend frontend || true
