name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: /www/wwwroot/planningpokerclub

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: |
            ~/docker-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build Docker images
        run: |
          cd /www/wwwroot/planningpokerclub
          docker build -t planningpokerclub-backend:latest -f backend/Dockerfile .
          docker build -t planningpokerclub-frontend:latest -f frontend/Dockerfile .

      - name: Run backend and frontend containers
        run: |
          docker run -d --name backend -p 7050:7050 --env-file /www/wwwroot/planningpokerclub/backend/.env planningpokerclub-backend:latest
          docker run -d --name frontend -p 7051:7051 --env-file /www/wwwroot/planningpokerclub/frontend/.env planningpokerclub-frontend:latest

      - name: Deploy to VPS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_USER: ${{ secrets.VPS_USER }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_HOST << 'EOF'
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            cd /path/on/vps
            docker-compose down
            docker-compose up -d
          EOF

      - name: Clean up
        run: |
          docker stop backend
          docker rm backend
          docker stop frontend
          docker rm frontend
